# Generated by Django 4.0 on 2021-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(max_length=15)),
                ('info', models.TextField(max_length=300)),
                ('upload', models.ImageField(upload_to='product_images')),
                ('links', models.URLField()),
            ],
        ),
    ]
