# Generated by Django 4.0 on 2021-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField(max_length=15)),
                ('info', models.TextField(max_length=300)),
                ('upload', models.ImageField(upload_to='equip_images')),
                ('links', models.URLField()),
            ],
        ),
    ]
