# Generated by Django 4.0 on 2021-12-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_equip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equip',
        ),
    ]
